import logging

HOST = '0.0.0.0'
PORT = 7477
MIN_RAID_LEVEL = 1
WEBHOOK_URL = 'http://localhost:4000'
TELEPORT_DELAY_SECONDS = 60
LOCATIONS_CSV_FILENAME = 'locations.csv'
SEEN_RAIDS_FILENAME = 'seen.cache'
LOG_LEVEL = logging.INFO
IGNORED_GYMS = []
